<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SwingAdviser.Application\SwingAdviser.Application.csproj" />
    <ProjectReference Include="..\SwingAdviser.Infrastructure\SwingAdviser.Infrastructure.csproj" />
    <PackageReference Include="MahApps.Metro" Version="2.4.11" />
  </ItemGroup>

</Project>
