// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SwingAdviser.Infrastructure.Persistence;

#nullable disable

namespace SwingAdviser.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SwingAdviserDbContext))]
    [Migration("20260830090259_AddHoldingEvaluationSchemaStep5")]
    partial class AddHoldingEvaluationSchemaStep5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.15");

            modelBuilder.Entity("SwingAdviser.Domain.Analysis.AnalysisInputManifest", b =>
                {
                    b.Property<int>("ManifestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("manifest_id");

                    b.Property<string>("AnalyzedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("analyzed_at_utc");

                    b.Property<int>("BarCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("bar_count");

                    b.Property<string>("CorporateActionSetHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("corporate_action_set_hash");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("EvaluationBarDate")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("evaluation_bar_date");

                    b.Property<string>("FirstBarDate")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("first_bar_date");

                    b.Property<int>("InstrumentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("instrument_id");

                    b.Property<string>("LastBarDate")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("last_bar_date");

                    b.Property<string>("ManifestHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("manifest_hash");

                    b.Property<string>("PriceRevisionSetHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("price_revision_set_hash");

                    b.HasKey("ManifestId")
                        .HasName("pk_analysis_input_manifests");

                    b.HasIndex("InstrumentId", "EvaluationBarDate", "AnalyzedAtUtc", "ManifestHash")
                        .IsUnique()
                        .HasDatabaseName("ix_analysis_input_manifests_instrument_id_evaluation_bar_date_analyzed_at_utc_manifest_hash");

                    b.ToTable("analysis_input_manifests", (string)null);
                });

            modelBuilder.Entity("SwingAdviser.Domain.Analysis.AnalysisInputManifestBar", b =>
                {
                    b.Property<int>("ManifestId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("manifest_id");

                    b.Property<string>("TradingDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("trading_date");

                    b.Property<int>("DailyBarId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("daily_bar_id");

                    b.HasKey("ManifestId", "TradingDate")
                        .HasName("pk_analysis_input_manifest_bars");

                    b.HasIndex("DailyBarId")
                        .HasDatabaseName("ix_analysis_input_manifest_bars_daily_bar_id");

                    b.ToTable("analysis_input_manifest_bars", (string)null);
                });

            modelBuilder.Entity("SwingAdviser.Domain.Analysis.AnalysisInputManifestCorporateAction", b =>
                {
                    b.Property<int>("ManifestId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("manifest_id");

                    b.Property<int>("CorporateActionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("corporate_action_id");

                    b.HasKey("ManifestId", "CorporateActionId")
                        .HasName("pk_analysis_input_manifest_corporate_actions");

                    b.HasIndex("CorporateActionId")
                        .HasDatabaseName("ix_analysis_input_manifest_corporate_actions_corporate_action_id");

                    b.ToTable("analysis_input_manifest_corporate_actions", (string)null);
                });

            modelBuilder.Entity("SwingAdviser.Domain.Analysis.CandidateResult", b =>
                {
                    b.Property<int>("CandidateResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("candidate_result_id");

                    b.Property<string>("CandidateScoringEngineVersion")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("candidate_scoring_engine_version");

                    b.Property<string>("ConfidenceLabel")
                        .HasColumnType("TEXT")
                        .HasColumnName("confidence_label");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("direction");

                    b.Property<int>("IndicatorResultId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("indicator_result_id");

                    b.Property<int>("InstrumentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("instrument_id");

                    b.Property<bool>("Matched")
                        .HasColumnType("INTEGER")
                        .HasColumnName("matched");

                    b.Property<int?>("Score")
                        .HasColumnType("INTEGER")
                        .HasColumnName("score");

                    b.Property<string>("ScoreComponentsJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("score_components_json");

                    b.Property<string>("SignalPurpose")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("signal_purpose");

                    b.HasKey("CandidateResultId")
                        .HasName("pk_candidate_results");

                    b.HasIndex("InstrumentId")
                        .HasDatabaseName("ix_candidate_results_instrument_id");

                    b.HasIndex("IndicatorResultId", "Direction")
                        .IsUnique()
                        .HasDatabaseName("ix_candidate_results_indicator_result_id_direction");

                    b.ToTable("candidate_results", (string)null);
                });

            modelBuilder.Entity("SwingAdviser.Domain.Analysis.DailyUpdateRun", b =>
                {
                    b.Property<int>("DailyUpdateRunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("daily_update_run_id");

                    b.Property<string>("CompletedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("completed_at_utc");

                    b.Property<string>("StartedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("StepSummaryJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("step_summary_json");

                    b.HasKey("DailyUpdateRunId")
                        .HasName("pk_daily_update_runs");

                    b.ToTable("daily_update_runs", (string)null);
                });

            modelBuilder.Entity("SwingAdviser.Domain.Analysis.ExternalFetchResult", b =>
                {
                    b.Property<int>("FetchResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("fetch_result_id");

                    b.Property<string>("AttemptedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("attempted_at_utc");

                    b.Property<int?>("DailyUpdateRunId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("daily_update_run_id");

                    b.Property<string>("ErrorKind")
                        .HasColumnType("TEXT")
                        .HasColumnName("error_kind");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT")
                        .HasColumnName("error_message");

                    b.Property<int?>("InstrumentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("instrument_id");

                    b.Property<int?>("RecordCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("record_count");

                    b.Property<string>("SourceKind")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source_kind");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("FetchResultId")
                        .HasName("pk_external_fetch_results");

                    b.HasIndex("DailyUpdateRunId")
                        .HasDatabaseName("ix_external_fetch_results_daily_update_run_id");

                    b.HasIndex("InstrumentId")
                        .HasDatabaseName("ix_external_fetch_results_instrument_id");

                    b.ToTable("external_fetch_results", (string)null);
                });

            modelBuilder.Entity("SwingAdviser.Domain.Analysis.IndicatorResult", b =>
                {
                    b.Property<int>("IndicatorResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("indicator_result_id");

                    b.Property<string>("AnalyzedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("analyzed_at_utc");

                    b.Property<string>("Atr14")
                        .HasColumnType("TEXT")
                        .HasColumnName("atr14");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DataStatus")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("data_status");

                    b.Property<string>("Ema20")
                        .HasColumnType("TEXT")
                        .HasColumnName("ema20");

                    b.Property<string>("Ema200")
                        .HasColumnType("TEXT")
                        .HasColumnName("ema200");

                    b.Property<string>("Ema50")
                        .HasColumnType("TEXT")
                        .HasColumnName("ema50");

                    b.Property<string>("EvaluationBarDate")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("evaluation_bar_date");

                    b.Property<int>("HistoryAvailableCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("history_available_count");

                    b.Property<int>("HistoryRequiredCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("history_required_count");

                    b.Property<int>("InstrumentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("instrument_id");

                    b.Property<string>("MacdHistogram")
                        .HasColumnType("TEXT")
                        .HasColumnName("macd_histogram");

                    b.Property<string>("MacdLine")
                        .HasColumnType("TEXT")
                        .HasColumnName("macd_line");

                    b.Property<string>("MacdSignal")
                        .HasColumnType("TEXT")
                        .HasColumnName("macd_signal");

                    b.Property<int>("ManifestId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("manifest_id");

                    b.Property<string>("RawValuesJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("raw_values_json");

                    b.Property<int>("ScanRunId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("scan_run_id");

                    b.Property<int>("StrategyParameterSnapshotId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("strategy_parameter_snapshot_id");

                    b.Property<string>("VolumeRatio")
                        .HasColumnType("TEXT")
                        .HasColumnName("volume_ratio");

                    b.Property<string>("VolumeRatioStatus")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("volume_ratio_status");

                    b.Property<string>("VolumeReferenceAverage")
                        .HasColumnType("TEXT")
                        .HasColumnName("volume_reference_average");

                    b.HasKey("IndicatorResultId")
                        .HasName("pk_indicator_results");

                    b.HasIndex("ManifestId")
                        .HasDatabaseName("ix_indicator_results_manifest_id");

                    b.HasIndex("ScanRunId")
                        .HasDatabaseName("ix_indicator_results_scan_run_id");

                    b.HasIndex("StrategyParameterSnapshotId")
                        .HasDatabaseName("ix_indicator_results_strategy_parameter_snapshot_id");

                    b.HasIndex("InstrumentId", "EvaluationBarDate", "AnalyzedAtUtc", "StrategyParameterSnapshotId")
                        .IsUnique()
                        .HasDatabaseName("ix_indicator_results_instrument_id_evaluation_bar_date_analyzed_at_utc_strategy_parameter_snapshot_id");

                    b.ToTable("indicator_results", (string)null);
                });

            modelBuilder.Entity("SwingAdviser.Domain.Analysis.ScanExclusion", b =>
                {
                    b.Property<int>("ScanExclusionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("scan_exclusion_id");

                    b.Property<int?>("HistoryAvailableCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("history_available_count");

                    b.Property<int?>("HistoryRequiredCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("history_required_count");

                    b.Property<int>("InstrumentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("instrument_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("reason");

                    b.Property<int>("ScanRunId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("scan_run_id");

                    b.HasKey("ScanExclusionId")
                        .HasName("pk_scan_exclusions");

                    b.HasIndex("InstrumentId")
                        .HasDatabaseName("ix_scan_exclusions_instrument_id");

                    b.HasIndex("ScanRunId", "InstrumentId")
                        .IsUnique()
                        .HasDatabaseName("ix_scan_exclusions_scan_run_id_instrument_id");

                    b.ToTable("scan_exclusions", (string)null);
                });

            modelBuilder.Entity("SwingAdviser.Domain.Analysis.ScanRun", b =>
                {
                    b.Property<int>("ScanRunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("scan_run_id");

                    b.Property<string>("CompletedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("completed_at_utc");

                    b.Property<int?>("DailyUpdateRunId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("daily_update_run_id");

                    b.Property<int>("FailedCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("failed_count");

                    b.Property<string>("RunType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("run_type");

                    b.Property<string>("StartedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<int>("SucceededCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("succeeded_count");

                    b.Property<int>("TotalInstruments")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_instruments");

                    b.Property<string>("UniverseDefinitionHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("universe_definition_hash");

                    b.HasKey("ScanRunId")
                        .HasName("pk_scan_runs");

                    b.HasIndex("DailyUpdateRunId")
                        .HasDatabaseName("ix_scan_runs_daily_update_run_id");

                    b.ToTable("scan_runs", (string)null);
                });

            modelBuilder.Entity("SwingAdviser.Domain.Analysis.StrategyParameterSnapshot", b =>
                {
                    b.Property<int>("StrategyParameterSnapshotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("strategy_parameter_snapshot_id");

                    b.Property<string>("CandidateScoringEngineVersion")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("candidate_scoring_engine_version");

                    b.Property<string>("ContentSha256")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content_sha256");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("IndicatorEngineVersion")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("indicator_engine_version");

                    b.Property<string>("NormalizedParametersJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("normalized_parameters_json");

                    b.Property<string>("StrategyKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("strategy_key");

                    b.Property<string>("StrategyVersion")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("strategy_version");

                    b.HasKey("StrategyParameterSnapshotId")
                        .HasName("pk_strategy_parameter_snapshots");

                    b.HasIndex("ContentSha256")
                        .IsUnique()
                        .HasDatabaseName("ix_strategy_parameter_snapshots_content_sha256");

                    b.ToTable("strategy_parameter_snapshots", (string)null);
                });

            modelBuilder.Entity("SwingAdviser.Domain.MarketData.CorporateAction", b =>
                {
                    b.Property<int>("CorporateActionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("corporate_action_id");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("action_type");

                    b.Property<string>("AnnouncedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("announced_at_utc");

                    b.Property<string>("AvailableAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("available_at_utc");

                    b.Property<string>("Currency")
                        .HasColumnType("TEXT")
                        .HasColumnName("currency");

                    b.Property<string>("DividendAmountPerShare")
                        .HasColumnType("TEXT")
                        .HasColumnName("dividend_amount_per_share");

                    b.Property<string>("EffectiveDate")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("effective_date");

                    b.Property<string>("FirstObservedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("first_observed_at_utc");

                    b.Property<int>("InstrumentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("instrument_id");

                    b.Property<string>("RecordedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("recorded_at_utc");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER")
                        .HasColumnName("revision");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source");

                    b.Property<string>("SourceEventId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source_event_id");

                    b.Property<int?>("SplitRatioDenominator")
                        .HasColumnType("INTEGER")
                        .HasColumnName("split_ratio_denominator");

                    b.Property<int?>("SplitRatioNumerator")
                        .HasColumnType("INTEGER")
                        .HasColumnName("split_ratio_numerator");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<int?>("SupersedesId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("supersedes_id");

                    b.HasKey("CorporateActionId")
                        .HasName("pk_corporate_actions");

                    b.HasIndex("SupersedesId")
                        .HasDatabaseName("ix_corporate_actions_supersedes_id");

                    b.HasIndex("InstrumentId", "SourceEventId", "Revision")
                        .IsUnique()
                        .HasDatabaseName("ix_corporate_actions_instrument_id_source_event_id_revision");

                    b.ToTable("corporate_actions", (string)null);
                });

            modelBuilder.Entity("SwingAdviser.Domain.MarketData.DailyBar", b =>
                {
                    b.Property<int>("DailyBarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("daily_bar_id");

                    b.Property<string>("AdjClose")
                        .HasColumnType("TEXT")
                        .HasColumnName("adj_close");

                    b.Property<string>("Close")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("close");

                    b.Property<string>("FetchedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("fetched_at_utc");

                    b.Property<string>("High")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("high");

                    b.Property<int>("InstrumentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("instrument_id");

                    b.Property<string>("Low")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("low");

                    b.Property<string>("Open")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("open");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER")
                        .HasColumnName("revision");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<int?>("SupersedesId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("supersedes_id");

                    b.Property<string>("TradingDate")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("trading_date");

                    b.Property<long>("Volume")
                        .HasColumnType("INTEGER")
                        .HasColumnName("volume");

                    b.HasKey("DailyBarId")
                        .HasName("pk_daily_bars");

                    b.HasIndex("SupersedesId")
                        .HasDatabaseName("ix_daily_bars_supersedes_id");

                    b.HasIndex("InstrumentId", "TradingDate", "Revision")
                        .IsUnique()
                        .HasDatabaseName("ix_daily_bars_instrument_id_trading_date_revision");

                    b.ToTable("daily_bars", (string)null);
                });

            modelBuilder.Entity("SwingAdviser.Domain.MarketData.FundamentalDataSnapshot", b =>
                {
                    b.Property<int>("FundamentalSnapshotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("fundamental_snapshot_id");

                    b.Property<string>("AdditionalMetricsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("additional_metrics_json");

                    b.Property<string>("DividendYield")
                        .HasColumnType("TEXT")
                        .HasColumnName("dividend_yield");

                    b.Property<string>("FetchedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("fetched_at_utc");

                    b.Property<int>("InstrumentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("instrument_id");

                    b.Property<string>("MarketCap")
                        .HasColumnType("TEXT")
                        .HasColumnName("market_cap");

                    b.Property<string>("Pbr")
                        .HasColumnType("TEXT")
                        .HasColumnName("pbr");

                    b.Property<string>("Per")
                        .HasColumnType("TEXT")
                        .HasColumnName("per");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source");

                    b.HasKey("FundamentalSnapshotId")
                        .HasName("pk_fundamental_data_snapshots");

                    b.HasIndex("InstrumentId")
                        .HasDatabaseName("ix_fundamental_data_snapshots_instrument_id");

                    b.ToTable("fundamental_data_snapshots", (string)null);
                });

            modelBuilder.Entity("SwingAdviser.Domain.MarketData.Instrument", b =>
                {
                    b.Property<int>("InstrumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("instrument_id");

                    b.Property<string>("FirstObservedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("first_observed_at_utc");

                    b.HasKey("InstrumentId")
                        .HasName("pk_instruments");

                    b.ToTable("instruments", (string)null);
                });

            modelBuilder.Entity("SwingAdviser.Domain.MarketData.InstrumentMasterRevision", b =>
                {
                    b.Property<int>("InstrumentMasterRevisionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("instrument_master_revision_id");

                    b.Property<string>("AvailableAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("available_at_utc");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<string>("EffectiveAtDate")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("effective_at_date");

                    b.Property<int>("InstrumentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("instrument_id");

                    b.Property<string>("InstrumentType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("instrument_type");

                    b.Property<string>("ListedStatus")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("listed_status");

                    b.Property<string>("MarketSegment")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("market_segment");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("RecordedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("recorded_at_utc");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER")
                        .HasColumnName("revision");

                    b.Property<string>("ScanEligibility")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("scan_eligibility");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source");

                    b.Property<string>("SourceFileHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source_file_hash");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<int?>("SupersedesRevisionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("supersedes_revision_id");

                    b.HasKey("InstrumentMasterRevisionId")
                        .HasName("pk_instrument_master_revisions");

                    b.HasIndex("SupersedesRevisionId")
                        .HasDatabaseName("ix_instrument_master_revisions_supersedes_revision_id");

                    b.HasIndex("InstrumentId", "Revision")
                        .IsUnique()
                        .HasDatabaseName("ix_instrument_master_revisions_instrument_id_revision");

                    b.ToTable("instrument_master_revisions", (string)null);
                });

            modelBuilder.Entity("SwingAdviser.Domain.MarketData.MarginRegulationRevision", b =>
                {
                    b.Property<int>("MarginRegulationRevisionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("margin_regulation_revision_id");

                    b.Property<string>("AvailableAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("available_at_utc");

                    b.Property<string>("EffectiveAtDate")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("effective_at_date");

                    b.Property<string>("GeneralMarginEligible")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("general_margin_eligible");

                    b.Property<int>("InstrumentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("instrument_id");

                    b.Property<string>("RecordedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("recorded_at_utc");

                    b.Property<string>("RegulationFlagsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("regulation_flags_json");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER")
                        .HasColumnName("revision");

                    b.Property<string>("ShortSellEligible")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("short_sell_eligible");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<int?>("SupersedesRevisionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("supersedes_revision_id");

                    b.Property<string>("SystemMarginEligible")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("system_margin_eligible");

                    b.HasKey("MarginRegulationRevisionId")
                        .HasName("pk_margin_regulation_revisions");

                    b.HasIndex("SupersedesRevisionId")
                        .HasDatabaseName("ix_margin_regulation_revisions_supersedes_revision_id");

                    b.HasIndex("InstrumentId", "Revision")
                        .IsUnique()
                        .HasDatabaseName("ix_margin_regulation_revisions_instrument_id_revision");

                    b.ToTable("margin_regulation_revisions", (string)null);
                });

            modelBuilder.Entity("SwingAdviser.Domain.Positions.MarginLot", b =>
                {
                    b.Property<int>("MarginLotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("margin_lot_id");

                    b.Property<string>("CurrentQuantity")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("current_quantity");

                    b.Property<int>("OpenedQuantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("opened_quantity");

                    b.Property<int>("OpeningTradeExecutionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("opening_trade_execution_id");

                    b.Property<int>("PositionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("position_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("MarginLotId")
                        .HasName("pk_margin_lots");

                    b.HasIndex("OpeningTradeExecutionId")
                        .IsUnique()
                        .HasDatabaseName("ix_margin_lots_opening_trade_execution_id");

                    b.HasIndex("PositionId")
                        .HasDatabaseName("ix_margin_lots_position_id");

                    b.ToTable("margin_lots", (string)null);
                });

            modelBuilder.Entity("SwingAdviser.Domain.Positions.MarginLotContractTermRevision", b =>
                {
                    b.Property<int>("ContractTermRevisionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("contract_term_revision_id");

                    b.Property<string>("Broker")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("broker");

                    b.Property<string>("ConfirmedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("confirmed_at_utc");

                    b.Property<string>("Evidence")
                        .HasColumnType("TEXT")
                        .HasColumnName("evidence");

                    b.Property<string>("FinalRepaymentDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("final_repayment_date");

                    b.Property<string>("MarginCategory")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("margin_category");

                    b.Property<int>("MarginLotId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("margin_lot_id");

                    b.Property<string>("Product")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("product");

                    b.Property<string>("RecordedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("recorded_at_utc");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER")
                        .HasColumnName("revision");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<int?>("SupersedesRevisionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("supersedes_revision_id");

                    b.Property<string>("TermType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("term_type");

                    b.HasKey("ContractTermRevisionId")
                        .HasName("pk_margin_lot_contract_term_revisions");

                    b.HasIndex("SupersedesRevisionId")
                        .HasDatabaseName("ix_margin_lot_contract_term_revisions_supersedes_revision_id");

                    b.HasIndex("MarginLotId", "Revision")
                        .IsUnique()
                        .HasDatabaseName("ix_margin_lot_contract_term_revisions_margin_lot_id_revision");

                    b.ToTable("margin_lot_contract_term_revisions", (string)null);
                });

            modelBuilder.Entity("SwingAdviser.Domain.Positions.Position", b =>
                {
                    b.Property<int>("PositionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("position_id");

                    b.Property<string>("AppliedStrategyKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("applied_strategy_key");

                    b.Property<string>("AppliedStrategyVersion")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("applied_strategy_version");

                    b.Property<string>("ClosedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("closed_at_utc");

                    b.Property<int>("InstrumentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("instrument_id");

                    b.Property<string>("Memo")
                        .HasColumnType("TEXT")
                        .HasColumnName("memo");

                    b.Property<string>("OpenedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("opened_at_utc");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("side");

                    b.Property<int?>("SourceCandidateResultId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("source_candidate_result_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("PositionId")
                        .HasName("pk_positions");

                    b.HasIndex("InstrumentId")
                        .HasDatabaseName("ix_positions_instrument_id");

                    b.HasIndex("SourceCandidateResultId")
                        .HasDatabaseName("ix_positions_source_candidate_result_id");

                    b.ToTable("positions", (string)null);
                });

            modelBuilder.Entity("SwingAdviser.Domain.Positions.PositionCorporateActionAdjustment", b =>
                {
                    b.Property<int>("AdjustmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("adjustment_id");

                    b.Property<string>("AppliedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("applied_at_utc");

                    b.Property<string>("AtrBasisAfter")
                        .HasColumnType("TEXT")
                        .HasColumnName("atr_basis_after");

                    b.Property<string>("AtrBasisBefore")
                        .HasColumnType("TEXT")
                        .HasColumnName("atr_basis_before");

                    b.Property<int>("CorporateActionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("corporate_action_id");

                    b.Property<string>("CostBasisAfter")
                        .HasColumnType("TEXT")
                        .HasColumnName("cost_basis_after");

                    b.Property<string>("CostBasisBefore")
                        .HasColumnType("TEXT")
                        .HasColumnName("cost_basis_before");

                    b.Property<int>("MarginLotId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("margin_lot_id");

                    b.Property<string>("QuantityAfter")
                        .HasColumnType("TEXT")
                        .HasColumnName("quantity_after");

                    b.Property<string>("QuantityBefore")
                        .HasColumnType("TEXT")
                        .HasColumnName("quantity_before");

                    b.Property<string>("Ratio")
                        .HasColumnType("TEXT")
                        .HasColumnName("ratio");

                    b.Property<string>("ReconciliationStatus")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("reconciliation_status");

                    b.Property<string>("StopPriceAfter")
                        .HasColumnType("TEXT")
                        .HasColumnName("stop_price_after");

                    b.Property<string>("StopPriceBefore")
                        .HasColumnType("TEXT")
                        .HasColumnName("stop_price_before");

                    b.Property<string>("TakeProfitPriceAfter")
                        .HasColumnType("TEXT")
                        .HasColumnName("take_profit_price_after");

                    b.Property<string>("TakeProfitPriceBefore")
                        .HasColumnType("TEXT")
                        .HasColumnName("take_profit_price_before");

                    b.HasKey("AdjustmentId")
                        .HasName("pk_position_corporate_action_adjustments");

                    b.HasIndex("CorporateActionId")
                        .HasDatabaseName("ix_position_corporate_action_adjustments_corporate_action_id");

                    b.HasIndex("MarginLotId", "CorporateActionId")
                        .IsUnique()
                        .HasDatabaseName("ix_position_corporate_action_adjustments_margin_lot_id_corporate_action_id");

                    b.ToTable("position_corporate_action_adjustments", (string)null);
                });

            modelBuilder.Entity("SwingAdviser.Domain.Positions.TradeExecution", b =>
                {
                    b.Property<int>("TradeExecutionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("trade_execution_id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("currency");

                    b.Property<string>("EnteredAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("entered_at_utc");

                    b.Property<string>("ExecutedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("executed_at");

                    b.Property<string>("ExecutionRole")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("execution_role");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<int>("PositionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("position_id");

                    b.Property<int?>("PrefilledFromCandidateResultId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("prefilled_from_candidate_result_id");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("price");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quantity");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER")
                        .HasColumnName("revision");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<int?>("SupersedesId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("supersedes_id");

                    b.HasKey("TradeExecutionId")
                        .HasName("pk_trade_executions");

                    b.HasIndex("PositionId")
                        .HasDatabaseName("ix_trade_executions_position_id");

                    b.HasIndex("PrefilledFromCandidateResultId")
                        .HasDatabaseName("ix_trade_executions_prefilled_from_candidate_result_id");

                    b.HasIndex("SupersedesId")
                        .HasDatabaseName("ix_trade_executions_supersedes_id");

                    b.ToTable("trade_executions", (string)null);
                });

            modelBuilder.Entity("SwingAdviser.Domain.Positions.TradeExecutionLotAllocation", b =>
                {
                    b.Property<int>("AllocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("allocation_id");

                    b.Property<string>("EffectiveAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("effective_at_utc");

                    b.Property<int>("MarginLotId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("margin_lot_id");

                    b.Property<string>("Quantity")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("quantity");

                    b.Property<string>("RecordedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("recorded_at_utc");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER")
                        .HasColumnName("revision");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<int?>("SupersedesId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("supersedes_id");

                    b.Property<int>("TradeExecutionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("trade_execution_id");

                    b.HasKey("AllocationId")
                        .HasName("pk_trade_execution_lot_allocations");

                    b.HasIndex("MarginLotId")
                        .HasDatabaseName("ix_trade_execution_lot_allocations_margin_lot_id");

                    b.HasIndex("SupersedesId")
                        .HasDatabaseName("ix_trade_execution_lot_allocations_supersedes_id");

                    b.HasIndex("TradeExecutionId", "MarginLotId", "Revision")
                        .IsUnique()
                        .HasDatabaseName("ix_trade_execution_lot_allocations_trade_execution_id_margin_lot_id_revision");

                    b.ToTable("trade_execution_lot_allocations", (string)null);
                });

            modelBuilder.Entity("SwingAdviser.Domain.Risk.LotHoldingEvaluation", b =>
                {
                    b.Property<int>("LotEvaluationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("lot_evaluation_id");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("DailyBarId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("daily_bar_id");

                    b.Property<string>("Decision")
                        .HasColumnType("TEXT")
                        .HasColumnName("decision");

                    b.Property<string>("DiagnosticsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("diagnostics_json");

                    b.Property<string>("Ema20ReversalState")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ema20reversal_state");

                    b.Property<string>("EvaluatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("evaluated_at_utc");

                    b.Property<string>("EvaluationBarDate")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("evaluation_bar_date");

                    b.Property<string>("EvaluationEvidenceJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("evaluation_evidence_json");

                    b.Property<string>("EvaluationOutcome")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("evaluation_outcome");

                    b.Property<string>("MacdReversalState")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("macd_reversal_state");

                    b.Property<int>("MarginLotId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("margin_lot_id");

                    b.Property<string>("PartialExitCandidateQuantity")
                        .HasColumnType("TEXT")
                        .HasColumnName("partial_exit_candidate_quantity");

                    b.Property<string>("PartialExitStatus")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("partial_exit_status");

                    b.Property<int>("PositionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("position_id");

                    b.Property<string>("PriorTargetFirstReachBarDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("prior_target_first_reach_bar_date");

                    b.Property<string>("PriorTargetReachState")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("prior_target_reach_state");

                    b.Property<int>("RiskPlanRevisionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("risk_plan_revision_id");

                    b.Property<bool>("StopReachedToday")
                        .HasColumnType("INTEGER")
                        .HasColumnName("stop_reached_today");

                    b.Property<bool>("TargetReachedToday")
                        .HasColumnType("INTEGER")
                        .HasColumnName("target_reached_today");

                    b.Property<string>("TechnicalReversalState")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("technical_reversal_state");

                    b.HasKey("LotEvaluationId")
                        .HasName("pk_lot_holding_evaluations");

                    b.HasIndex("DailyBarId")
                        .HasDatabaseName("ix_lot_holding_evaluations_daily_bar_id");

                    b.HasIndex("PositionId")
                        .HasDatabaseName("ix_lot_holding_evaluations_position_id");

                    b.HasIndex("RiskPlanRevisionId")
                        .HasDatabaseName("ix_lot_holding_evaluations_risk_plan_revision_id");

                    b.HasIndex("MarginLotId", "EvaluationBarDate", "EvaluatedAtUtc")
                        .IsUnique()
                        .HasDatabaseName("ix_lot_holding_evaluations_margin_lot_id_evaluation_bar_date_evaluated_at_utc");

                    b.ToTable("lot_holding_evaluations", (string)null);
                });

            modelBuilder.Entity("SwingAdviser.Domain.Risk.PositionHoldingEvaluation", b =>
                {
                    b.Property<int>("PositionEvaluationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("position_evaluation_id");

                    b.Property<string>("AggregatedDecision")
                        .HasColumnType("TEXT")
                        .HasColumnName("aggregated_decision");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("EvaluatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("evaluated_at_utc");

                    b.Property<string>("EvaluationBarDate")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("evaluation_bar_date");

                    b.Property<string>("EvaluationOutcome")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("evaluation_outcome");

                    b.Property<string>("LotEvaluationsJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("lot_evaluations_json");

                    b.Property<string>("PartialExitStatus")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("partial_exit_status");

                    b.Property<string>("PartialExitTotalCandidateQuantity")
                        .HasColumnType("TEXT")
                        .HasColumnName("partial_exit_total_candidate_quantity");

                    b.Property<int>("PositionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("position_id");

                    b.HasKey("PositionEvaluationId")
                        .HasName("pk_position_holding_evaluations");

                    b.HasIndex("PositionId", "EvaluationBarDate", "EvaluatedAtUtc")
                        .IsUnique()
                        .HasDatabaseName("ix_position_holding_evaluations_position_id_evaluation_bar_date_evaluated_at_utc");

                    b.ToTable("position_holding_evaluations", (string)null);
                });

            modelBuilder.Entity("SwingAdviser.Domain.Risk.RiskBasisSnapshot", b =>
                {
                    b.Property<int>("RiskBasisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("risk_basis_id");

                    b.Property<string>("AtrAlgorithmVersion")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("atr_algorithm_version");

                    b.Property<string>("AtrBasis")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("atr_basis");

                    b.Property<int>("AtrPeriod")
                        .HasColumnType("INTEGER")
                        .HasColumnName("atr_period");

                    b.Property<string>("AtrReferenceBarDate")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("atr_reference_bar_date");

                    b.Property<string>("ContentSha256")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content_sha256");

                    b.Property<string>("CorporateActionSetHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("corporate_action_set_hash");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("currency");

                    b.Property<string>("EntryBasisPrice")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("entry_basis_price");

                    b.Property<int?>("ManualOpenAnalysisInputManifestId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("manual_open_analysis_input_manifest_id");

                    b.Property<int>("MarginLotId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("margin_lot_id");

                    b.Property<string>("PriceUnitBasisSha256")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("price_unit_basis_sha256");

                    b.Property<int?>("SourceCandidateResultId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("source_candidate_result_id");

                    b.Property<int?>("SourceIndicatorResultId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("source_indicator_result_id");

                    b.Property<int>("StrategyParameterSnapshotId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("strategy_parameter_snapshot_id");

                    b.HasKey("RiskBasisId")
                        .HasName("pk_risk_basis_snapshots");

                    b.HasIndex("ManualOpenAnalysisInputManifestId")
                        .HasDatabaseName("ix_risk_basis_snapshots_manual_open_analysis_input_manifest_id");

                    b.HasIndex("MarginLotId")
                        .IsUnique()
                        .HasDatabaseName("ix_risk_basis_snapshots_margin_lot_id");

                    b.HasIndex("SourceCandidateResultId")
                        .HasDatabaseName("ix_risk_basis_snapshots_source_candidate_result_id");

                    b.HasIndex("SourceIndicatorResultId")
                        .HasDatabaseName("ix_risk_basis_snapshots_source_indicator_result_id");

                    b.HasIndex("StrategyParameterSnapshotId")
                        .HasDatabaseName("ix_risk_basis_snapshots_strategy_parameter_snapshot_id");

                    b.ToTable("risk_basis_snapshots", (string)null);
                });

            modelBuilder.Entity("SwingAdviser.Domain.Risk.RiskPlan", b =>
                {
                    b.Property<int>("RiskPlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("risk_plan_id");

                    b.Property<string>("EffectiveAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("effective_at_utc");

                    b.Property<int>("MarginLotId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("margin_lot_id");

                    b.Property<string>("PartialTakeProfitFraction")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("partial_take_profit_fraction");

                    b.Property<string>("PlanKind")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("plan_kind");

                    b.Property<string>("RecordedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("recorded_at_utc");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER")
                        .HasColumnName("revision");

                    b.Property<int>("RiskBasisId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("risk_basis_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("StopPrice")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("stop_price");

                    b.Property<int?>("SupersedesRevisionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("supersedes_revision_id");

                    b.Property<string>("TakeProfitPrice")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("take_profit_price");

                    b.Property<int?>("TriggerAllocationId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("trigger_allocation_id");

                    b.Property<int?>("TriggerTradeExecutionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("trigger_trade_execution_id");

                    b.HasKey("RiskPlanId")
                        .HasName("pk_risk_plans");

                    b.HasIndex("RiskBasisId")
                        .HasDatabaseName("ix_risk_plans_risk_basis_id");

                    b.HasIndex("SupersedesRevisionId")
                        .HasDatabaseName("ix_risk_plans_supersedes_revision_id");

                    b.HasIndex("TriggerAllocationId")
                        .HasDatabaseName("ix_risk_plans_trigger_allocation_id");

                    b.HasIndex("TriggerTradeExecutionId")
                        .HasDatabaseName("ix_risk_plans_trigger_trade_execution_id");

                    b.HasIndex("MarginLotId", "Revision")
                        .IsUnique()
                        .HasDatabaseName("ix_risk_plans_margin_lot_id_revision");

                    b.ToTable("risk_plans", (string)null);
                });

            modelBuilder.Entity("SwingAdviser.Domain.Analysis.AnalysisInputManifest", b =>
                {
                    b.HasOne("SwingAdviser.Domain.MarketData.Instrument", "Instrument")
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_analysis_input_manifests_instruments_instrument_id");

                    b.Navigation("Instrument");
                });

            modelBuilder.Entity("SwingAdviser.Domain.Analysis.AnalysisInputManifestBar", b =>
                {
                    b.HasOne("SwingAdviser.Domain.MarketData.DailyBar", "DailyBar")
                        .WithMany()
                        .HasForeignKey("DailyBarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_analysis_input_manifest_bars_daily_bars_daily_bar_id");

                    b.HasOne("SwingAdviser.Domain.Analysis.AnalysisInputManifest", "Manifest")
                        .WithMany("Bars")
                        .HasForeignKey("ManifestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_analysis_input_manifest_bars_analysis_input_manifests_manifest_id");

                    b.Navigation("DailyBar");

                    b.Navigation("Manifest");
                });

            modelBuilder.Entity("SwingAdviser.Domain.Analysis.AnalysisInputManifestCorporateAction", b =>
                {
                    b.HasOne("SwingAdviser.Domain.MarketData.CorporateAction", "CorporateAction")
                        .WithMany()
                        .HasForeignKey("CorporateActionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_analysis_input_manifest_corporate_actions_corporate_actions_corporate_action_id");

                    b.HasOne("SwingAdviser.Domain.Analysis.AnalysisInputManifest", "Manifest")
                        .WithMany("CorporateActions")
                        .HasForeignKey("ManifestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_analysis_input_manifest_corporate_actions_analysis_input_manifests_manifest_id");

                    b.Navigation("CorporateAction");

                    b.Navigation("Manifest");
                });

            modelBuilder.Entity("SwingAdviser.Domain.Analysis.CandidateResult", b =>
                {
                    b.HasOne("SwingAdviser.Domain.Analysis.IndicatorResult", "IndicatorResult")
                        .WithMany("CandidateResults")
                        .HasForeignKey("IndicatorResultId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_candidate_results_indicator_results_indicator_result_id");

                    b.HasOne("SwingAdviser.Domain.MarketData.Instrument", "Instrument")
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_candidate_results_instruments_instrument_id");

                    b.Navigation("IndicatorResult");

                    b.Navigation("Instrument");
                });

            modelBuilder.Entity("SwingAdviser.Domain.Analysis.ExternalFetchResult", b =>
                {
                    b.HasOne("SwingAdviser.Domain.Analysis.DailyUpdateRun", "DailyUpdateRun")
                        .WithMany("ExternalFetchResults")
                        .HasForeignKey("DailyUpdateRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_external_fetch_results_daily_update_runs_daily_update_run_id");

                    b.HasOne("SwingAdviser.Domain.MarketData.Instrument", "Instrument")
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_external_fetch_results_instruments_instrument_id");

                    b.Navigation("DailyUpdateRun");

                    b.Navigation("Instrument");
                });

            modelBuilder.Entity("SwingAdviser.Domain.Analysis.IndicatorResult", b =>
                {
                    b.HasOne("SwingAdviser.Domain.MarketData.Instrument", "Instrument")
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_indicator_results_instruments_instrument_id");

                    b.HasOne("SwingAdviser.Domain.Analysis.AnalysisInputManifest", "Manifest")
                        .WithMany("IndicatorResults")
                        .HasForeignKey("ManifestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_indicator_results_analysis_input_manifests_manifest_id");

                    b.HasOne("SwingAdviser.Domain.Analysis.ScanRun", "ScanRun")
                        .WithMany("IndicatorResults")
                        .HasForeignKey("ScanRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_indicator_results_scan_runs_scan_run_id");

                    b.HasOne("SwingAdviser.Domain.Analysis.StrategyParameterSnapshot", "StrategyParameterSnapshot")
                        .WithMany("IndicatorResults")
                        .HasForeignKey("StrategyParameterSnapshotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_indicator_results_strategy_parameter_snapshots_strategy_parameter_snapshot_id");

                    b.Navigation("Instrument");

                    b.Navigation("Manifest");

                    b.Navigation("ScanRun");

                    b.Navigation("StrategyParameterSnapshot");
                });

            modelBuilder.Entity("SwingAdviser.Domain.Analysis.ScanExclusion", b =>
                {
                    b.HasOne("SwingAdviser.Domain.MarketData.Instrument", "Instrument")
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_scan_exclusions_instruments_instrument_id");

                    b.HasOne("SwingAdviser.Domain.Analysis.ScanRun", "ScanRun")
                        .WithMany("ScanExclusions")
                        .HasForeignKey("ScanRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_scan_exclusions_scan_runs_scan_run_id");

                    b.Navigation("Instrument");

                    b.Navigation("ScanRun");
                });

            modelBuilder.Entity("SwingAdviser.Domain.Analysis.ScanRun", b =>
                {
                    b.HasOne("SwingAdviser.Domain.Analysis.DailyUpdateRun", "DailyUpdateRun")
                        .WithMany("ScanRuns")
                        .HasForeignKey("DailyUpdateRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_scan_runs_daily_update_runs_daily_update_run_id");

                    b.Navigation("DailyUpdateRun");
                });

            modelBuilder.Entity("SwingAdviser.Domain.MarketData.CorporateAction", b =>
                {
                    b.HasOne("SwingAdviser.Domain.MarketData.Instrument", "Instrument")
                        .WithMany("CorporateActions")
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_corporate_actions_instruments_instrument_id");

                    b.HasOne("SwingAdviser.Domain.MarketData.CorporateAction", "Supersedes")
                        .WithMany()
                        .HasForeignKey("SupersedesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_corporate_actions_corporate_actions_supersedes_id");

                    b.Navigation("Instrument");

                    b.Navigation("Supersedes");
                });

            modelBuilder.Entity("SwingAdviser.Domain.MarketData.DailyBar", b =>
                {
                    b.HasOne("SwingAdviser.Domain.MarketData.Instrument", "Instrument")
                        .WithMany("DailyBars")
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_daily_bars_instruments_instrument_id");

                    b.HasOne("SwingAdviser.Domain.MarketData.DailyBar", "Supersedes")
                        .WithMany()
                        .HasForeignKey("SupersedesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_daily_bars_daily_bars_supersedes_id");

                    b.Navigation("Instrument");

                    b.Navigation("Supersedes");
                });

            modelBuilder.Entity("SwingAdviser.Domain.MarketData.FundamentalDataSnapshot", b =>
                {
                    b.HasOne("SwingAdviser.Domain.MarketData.Instrument", "Instrument")
                        .WithMany("FundamentalDataSnapshots")
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_fundamental_data_snapshots_instruments_instrument_id");

                    b.Navigation("Instrument");
                });

            modelBuilder.Entity("SwingAdviser.Domain.MarketData.InstrumentMasterRevision", b =>
                {
                    b.HasOne("SwingAdviser.Domain.MarketData.Instrument", "Instrument")
                        .WithMany("MasterRevisions")
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_instrument_master_revisions_instruments_instrument_id");

                    b.HasOne("SwingAdviser.Domain.MarketData.InstrumentMasterRevision", "SupersedesRevision")
                        .WithMany()
                        .HasForeignKey("SupersedesRevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_instrument_master_revisions_instrument_master_revisions_supersedes_revision_id");

                    b.Navigation("Instrument");

                    b.Navigation("SupersedesRevision");
                });

            modelBuilder.Entity("SwingAdviser.Domain.MarketData.MarginRegulationRevision", b =>
                {
                    b.HasOne("SwingAdviser.Domain.MarketData.Instrument", "Instrument")
                        .WithMany("MarginRegulationRevisions")
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_margin_regulation_revisions_instruments_instrument_id");

                    b.HasOne("SwingAdviser.Domain.MarketData.MarginRegulationRevision", "SupersedesRevision")
                        .WithMany()
                        .HasForeignKey("SupersedesRevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_margin_regulation_revisions_margin_regulation_revisions_supersedes_revision_id");

                    b.Navigation("Instrument");

                    b.Navigation("SupersedesRevision");
                });

            modelBuilder.Entity("SwingAdviser.Domain.Positions.MarginLot", b =>
                {
                    b.HasOne("SwingAdviser.Domain.Positions.TradeExecution", "OpeningTradeExecution")
                        .WithMany()
                        .HasForeignKey("OpeningTradeExecutionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_margin_lots_trade_executions_opening_trade_execution_id");

                    b.HasOne("SwingAdviser.Domain.Positions.Position", "Position")
                        .WithMany("MarginLots")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_margin_lots_positions_position_id");

                    b.Navigation("OpeningTradeExecution");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("SwingAdviser.Domain.Positions.MarginLotContractTermRevision", b =>
                {
                    b.HasOne("SwingAdviser.Domain.Positions.MarginLot", "MarginLot")
                        .WithMany("ContractTermRevisions")
                        .HasForeignKey("MarginLotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_margin_lot_contract_term_revisions_margin_lots_margin_lot_id");

                    b.HasOne("SwingAdviser.Domain.Positions.MarginLotContractTermRevision", "SupersedesRevision")
                        .WithMany()
                        .HasForeignKey("SupersedesRevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_margin_lot_contract_term_revisions_margin_lot_contract_term_revisions_supersedes_revision_id");

                    b.Navigation("MarginLot");

                    b.Navigation("SupersedesRevision");
                });

            modelBuilder.Entity("SwingAdviser.Domain.Positions.Position", b =>
                {
                    b.HasOne("SwingAdviser.Domain.MarketData.Instrument", "Instrument")
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_positions_instruments_instrument_id");

                    b.HasOne("SwingAdviser.Domain.Analysis.CandidateResult", "SourceCandidateResult")
                        .WithMany()
                        .HasForeignKey("SourceCandidateResultId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_positions_candidate_results_source_candidate_result_id");

                    b.Navigation("Instrument");

                    b.Navigation("SourceCandidateResult");
                });

            modelBuilder.Entity("SwingAdviser.Domain.Positions.PositionCorporateActionAdjustment", b =>
                {
                    b.HasOne("SwingAdviser.Domain.MarketData.CorporateAction", "CorporateAction")
                        .WithMany()
                        .HasForeignKey("CorporateActionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_position_corporate_action_adjustments_corporate_actions_corporate_action_id");

                    b.HasOne("SwingAdviser.Domain.Positions.MarginLot", "MarginLot")
                        .WithMany("CorporateActionAdjustments")
                        .HasForeignKey("MarginLotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_position_corporate_action_adjustments_margin_lots_margin_lot_id");

                    b.Navigation("CorporateAction");

                    b.Navigation("MarginLot");
                });

            modelBuilder.Entity("SwingAdviser.Domain.Positions.TradeExecution", b =>
                {
                    b.HasOne("SwingAdviser.Domain.Positions.Position", "Position")
                        .WithMany("TradeExecutions")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_trade_executions_positions_position_id");

                    b.HasOne("SwingAdviser.Domain.Analysis.CandidateResult", "PrefilledFromCandidateResult")
                        .WithMany()
                        .HasForeignKey("PrefilledFromCandidateResultId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_trade_executions_candidate_results_prefilled_from_candidate_result_id");

                    b.HasOne("SwingAdviser.Domain.Positions.TradeExecution", "Supersedes")
                        .WithMany()
                        .HasForeignKey("SupersedesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_trade_executions_trade_executions_supersedes_id");

                    b.Navigation("Position");

                    b.Navigation("PrefilledFromCandidateResult");

                    b.Navigation("Supersedes");
                });

            modelBuilder.Entity("SwingAdviser.Domain.Positions.TradeExecutionLotAllocation", b =>
                {
                    b.HasOne("SwingAdviser.Domain.Positions.MarginLot", "MarginLot")
                        .WithMany("TradeExecutionLotAllocations")
                        .HasForeignKey("MarginLotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_trade_execution_lot_allocations_margin_lots_margin_lot_id");

                    b.HasOne("SwingAdviser.Domain.Positions.TradeExecutionLotAllocation", "Supersedes")
                        .WithMany()
                        .HasForeignKey("SupersedesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_trade_execution_lot_allocations_trade_execution_lot_allocations_supersedes_id");

                    b.HasOne("SwingAdviser.Domain.Positions.TradeExecution", "TradeExecution")
                        .WithMany("LotAllocations")
                        .HasForeignKey("TradeExecutionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_trade_execution_lot_allocations_trade_executions_trade_execution_id");

                    b.Navigation("MarginLot");

                    b.Navigation("Supersedes");

                    b.Navigation("TradeExecution");
                });

            modelBuilder.Entity("SwingAdviser.Domain.Risk.LotHoldingEvaluation", b =>
                {
                    b.HasOne("SwingAdviser.Domain.MarketData.DailyBar", "DailyBar")
                        .WithMany()
                        .HasForeignKey("DailyBarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_lot_holding_evaluations_daily_bars_daily_bar_id");

                    b.HasOne("SwingAdviser.Domain.Positions.MarginLot", "MarginLot")
                        .WithMany()
                        .HasForeignKey("MarginLotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_lot_holding_evaluations_margin_lots_margin_lot_id");

                    b.HasOne("SwingAdviser.Domain.Positions.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_lot_holding_evaluations_positions_position_id");

                    b.HasOne("SwingAdviser.Domain.Risk.RiskPlan", "RiskPlanRevision")
                        .WithMany()
                        .HasForeignKey("RiskPlanRevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_lot_holding_evaluations_risk_plans_risk_plan_revision_id");

                    b.Navigation("DailyBar");

                    b.Navigation("MarginLot");

                    b.Navigation("Position");

                    b.Navigation("RiskPlanRevision");
                });

            modelBuilder.Entity("SwingAdviser.Domain.Risk.PositionHoldingEvaluation", b =>
                {
                    b.HasOne("SwingAdviser.Domain.Positions.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_position_holding_evaluations_positions_position_id");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("SwingAdviser.Domain.Risk.RiskBasisSnapshot", b =>
                {
                    b.HasOne("SwingAdviser.Domain.Analysis.AnalysisInputManifest", "ManualOpenAnalysisInputManifest")
                        .WithMany()
                        .HasForeignKey("ManualOpenAnalysisInputManifestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_risk_basis_snapshots_analysis_input_manifests_manual_open_analysis_input_manifest_id");

                    b.HasOne("SwingAdviser.Domain.Positions.MarginLot", "MarginLot")
                        .WithMany()
                        .HasForeignKey("MarginLotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_risk_basis_snapshots_margin_lots_margin_lot_id");

                    b.HasOne("SwingAdviser.Domain.Analysis.CandidateResult", "SourceCandidateResult")
                        .WithMany()
                        .HasForeignKey("SourceCandidateResultId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_risk_basis_snapshots_candidate_results_source_candidate_result_id");

                    b.HasOne("SwingAdviser.Domain.Analysis.IndicatorResult", "SourceIndicatorResult")
                        .WithMany()
                        .HasForeignKey("SourceIndicatorResultId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_risk_basis_snapshots_indicator_results_source_indicator_result_id");

                    b.HasOne("SwingAdviser.Domain.Analysis.StrategyParameterSnapshot", "StrategyParameterSnapshot")
                        .WithMany()
                        .HasForeignKey("StrategyParameterSnapshotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_risk_basis_snapshots_strategy_parameter_snapshots_strategy_parameter_snapshot_id");

                    b.Navigation("ManualOpenAnalysisInputManifest");

                    b.Navigation("MarginLot");

                    b.Navigation("SourceCandidateResult");

                    b.Navigation("SourceIndicatorResult");

                    b.Navigation("StrategyParameterSnapshot");
                });

            modelBuilder.Entity("SwingAdviser.Domain.Risk.RiskPlan", b =>
                {
                    b.HasOne("SwingAdviser.Domain.Positions.MarginLot", "MarginLot")
                        .WithMany()
                        .HasForeignKey("MarginLotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_risk_plans_margin_lots_margin_lot_id");

                    b.HasOne("SwingAdviser.Domain.Risk.RiskBasisSnapshot", "RiskBasis")
                        .WithMany()
                        .HasForeignKey("RiskBasisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_risk_plans_risk_basis_snapshots_risk_basis_id");

                    b.HasOne("SwingAdviser.Domain.Risk.RiskPlan", "SupersedesRevision")
                        .WithMany()
                        .HasForeignKey("SupersedesRevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_risk_plans_risk_plans_supersedes_revision_id");

                    b.HasOne("SwingAdviser.Domain.Positions.TradeExecutionLotAllocation", "TriggerAllocation")
                        .WithMany()
                        .HasForeignKey("TriggerAllocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_risk_plans_trade_execution_lot_allocations_trigger_allocation_id");

                    b.HasOne("SwingAdviser.Domain.Positions.TradeExecution", "TriggerTradeExecution")
                        .WithMany()
                        .HasForeignKey("TriggerTradeExecutionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_risk_plans_trade_executions_trigger_trade_execution_id");

                    b.Navigation("MarginLot");

                    b.Navigation("RiskBasis");

                    b.Navigation("SupersedesRevision");

                    b.Navigation("TriggerAllocation");

                    b.Navigation("TriggerTradeExecution");
                });

            modelBuilder.Entity("SwingAdviser.Domain.Analysis.AnalysisInputManifest", b =>
                {
                    b.Navigation("Bars");

                    b.Navigation("CorporateActions");

                    b.Navigation("IndicatorResults");
                });

            modelBuilder.Entity("SwingAdviser.Domain.Analysis.DailyUpdateRun", b =>
                {
                    b.Navigation("ExternalFetchResults");

                    b.Navigation("ScanRuns");
                });

            modelBuilder.Entity("SwingAdviser.Domain.Analysis.IndicatorResult", b =>
                {
                    b.Navigation("CandidateResults");
                });

            modelBuilder.Entity("SwingAdviser.Domain.Analysis.ScanRun", b =>
                {
                    b.Navigation("IndicatorResults");

                    b.Navigation("ScanExclusions");
                });

            modelBuilder.Entity("SwingAdviser.Domain.Analysis.StrategyParameterSnapshot", b =>
                {
                    b.Navigation("IndicatorResults");
                });

            modelBuilder.Entity("SwingAdviser.Domain.MarketData.Instrument", b =>
                {
                    b.Navigation("CorporateActions");

                    b.Navigation("DailyBars");

                    b.Navigation("FundamentalDataSnapshots");

                    b.Navigation("MarginRegulationRevisions");

                    b.Navigation("MasterRevisions");
                });

            modelBuilder.Entity("SwingAdviser.Domain.Positions.MarginLot", b =>
                {
                    b.Navigation("ContractTermRevisions");

                    b.Navigation("CorporateActionAdjustments");

                    b.Navigation("TradeExecutionLotAllocations");
                });

            modelBuilder.Entity("SwingAdviser.Domain.Positions.Position", b =>
                {
                    b.Navigation("MarginLots");

                    b.Navigation("TradeExecutions");
                });

            modelBuilder.Entity("SwingAdviser.Domain.Positions.TradeExecution", b =>
                {
                    b.Navigation("LotAllocations");
                });
#pragma warning restore 612, 618
        }
    }
}
