// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SwingAdviser.Infrastructure.Persistence;

#nullable disable

namespace SwingAdviser.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SwingAdviserDbContext))]
    [Migration("20260830084225_AddMarketDataSchemaStep1")]
    partial class AddMarketDataSchemaStep1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.15");

            modelBuilder.Entity("SwingAdviser.Domain.MarketData.CorporateAction", b =>
                {
                    b.Property<int>("CorporateActionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("corporate_action_id");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("action_type");

                    b.Property<string>("AnnouncedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("announced_at_utc");

                    b.Property<string>("AvailableAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("available_at_utc");

                    b.Property<string>("Currency")
                        .HasColumnType("TEXT")
                        .HasColumnName("currency");

                    b.Property<string>("DividendAmountPerShare")
                        .HasColumnType("TEXT")
                        .HasColumnName("dividend_amount_per_share");

                    b.Property<string>("EffectiveDate")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("effective_date");

                    b.Property<string>("FirstObservedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("first_observed_at_utc");

                    b.Property<int>("InstrumentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("instrument_id");

                    b.Property<string>("RecordedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("recorded_at_utc");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER")
                        .HasColumnName("revision");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source");

                    b.Property<string>("SourceEventId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source_event_id");

                    b.Property<int?>("SplitRatioDenominator")
                        .HasColumnType("INTEGER")
                        .HasColumnName("split_ratio_denominator");

                    b.Property<int?>("SplitRatioNumerator")
                        .HasColumnType("INTEGER")
                        .HasColumnName("split_ratio_numerator");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<int?>("SupersedesId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("supersedes_id");

                    b.HasKey("CorporateActionId")
                        .HasName("pk_corporate_actions");

                    b.HasIndex("SupersedesId")
                        .HasDatabaseName("ix_corporate_actions_supersedes_id");

                    b.HasIndex("InstrumentId", "SourceEventId", "Revision")
                        .IsUnique()
                        .HasDatabaseName("ix_corporate_actions_instrument_id_source_event_id_revision");

                    b.ToTable("corporate_actions", (string)null);
                });

            modelBuilder.Entity("SwingAdviser.Domain.MarketData.DailyBar", b =>
                {
                    b.Property<int>("DailyBarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("daily_bar_id");

                    b.Property<string>("AdjClose")
                        .HasColumnType("TEXT")
                        .HasColumnName("adj_close");

                    b.Property<string>("Close")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("close");

                    b.Property<string>("FetchedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("fetched_at_utc");

                    b.Property<string>("High")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("high");

                    b.Property<int>("InstrumentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("instrument_id");

                    b.Property<string>("Low")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("low");

                    b.Property<string>("Open")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("open");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER")
                        .HasColumnName("revision");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<int?>("SupersedesId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("supersedes_id");

                    b.Property<string>("TradingDate")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("trading_date");

                    b.Property<long>("Volume")
                        .HasColumnType("INTEGER")
                        .HasColumnName("volume");

                    b.HasKey("DailyBarId")
                        .HasName("pk_daily_bars");

                    b.HasIndex("SupersedesId")
                        .HasDatabaseName("ix_daily_bars_supersedes_id");

                    b.HasIndex("InstrumentId", "TradingDate", "Revision")
                        .IsUnique()
                        .HasDatabaseName("ix_daily_bars_instrument_id_trading_date_revision");

                    b.ToTable("daily_bars", (string)null);
                });

            modelBuilder.Entity("SwingAdviser.Domain.MarketData.FundamentalDataSnapshot", b =>
                {
                    b.Property<int>("FundamentalSnapshotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("fundamental_snapshot_id");

                    b.Property<string>("AdditionalMetricsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("additional_metrics_json");

                    b.Property<string>("DividendYield")
                        .HasColumnType("TEXT")
                        .HasColumnName("dividend_yield");

                    b.Property<string>("FetchedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("fetched_at_utc");

                    b.Property<int>("InstrumentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("instrument_id");

                    b.Property<string>("MarketCap")
                        .HasColumnType("TEXT")
                        .HasColumnName("market_cap");

                    b.Property<string>("Pbr")
                        .HasColumnType("TEXT")
                        .HasColumnName("pbr");

                    b.Property<string>("Per")
                        .HasColumnType("TEXT")
                        .HasColumnName("per");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source");

                    b.HasKey("FundamentalSnapshotId")
                        .HasName("pk_fundamental_data_snapshots");

                    b.HasIndex("InstrumentId")
                        .HasDatabaseName("ix_fundamental_data_snapshots_instrument_id");

                    b.ToTable("fundamental_data_snapshots", (string)null);
                });

            modelBuilder.Entity("SwingAdviser.Domain.MarketData.Instrument", b =>
                {
                    b.Property<int>("InstrumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("instrument_id");

                    b.Property<string>("FirstObservedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("first_observed_at_utc");

                    b.HasKey("InstrumentId")
                        .HasName("pk_instruments");

                    b.ToTable("instruments", (string)null);
                });

            modelBuilder.Entity("SwingAdviser.Domain.MarketData.InstrumentMasterRevision", b =>
                {
                    b.Property<int>("InstrumentMasterRevisionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("instrument_master_revision_id");

                    b.Property<string>("AvailableAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("available_at_utc");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<string>("EffectiveAtDate")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("effective_at_date");

                    b.Property<int>("InstrumentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("instrument_id");

                    b.Property<string>("InstrumentType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("instrument_type");

                    b.Property<string>("ListedStatus")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("listed_status");

                    b.Property<string>("MarketSegment")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("market_segment");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("RecordedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("recorded_at_utc");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER")
                        .HasColumnName("revision");

                    b.Property<string>("ScanEligibility")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("scan_eligibility");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source");

                    b.Property<string>("SourceFileHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source_file_hash");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<int?>("SupersedesRevisionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("supersedes_revision_id");

                    b.HasKey("InstrumentMasterRevisionId")
                        .HasName("pk_instrument_master_revisions");

                    b.HasIndex("SupersedesRevisionId")
                        .HasDatabaseName("ix_instrument_master_revisions_supersedes_revision_id");

                    b.HasIndex("InstrumentId", "Revision")
                        .IsUnique()
                        .HasDatabaseName("ix_instrument_master_revisions_instrument_id_revision");

                    b.ToTable("instrument_master_revisions", (string)null);
                });

            modelBuilder.Entity("SwingAdviser.Domain.MarketData.MarginRegulationRevision", b =>
                {
                    b.Property<int>("MarginRegulationRevisionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("margin_regulation_revision_id");

                    b.Property<string>("AvailableAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("available_at_utc");

                    b.Property<string>("EffectiveAtDate")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("effective_at_date");

                    b.Property<string>("GeneralMarginEligible")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("general_margin_eligible");

                    b.Property<int>("InstrumentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("instrument_id");

                    b.Property<string>("RecordedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("recorded_at_utc");

                    b.Property<string>("RegulationFlagsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("regulation_flags_json");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER")
                        .HasColumnName("revision");

                    b.Property<string>("ShortSellEligible")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("short_sell_eligible");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<int?>("SupersedesRevisionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("supersedes_revision_id");

                    b.Property<string>("SystemMarginEligible")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("system_margin_eligible");

                    b.HasKey("MarginRegulationRevisionId")
                        .HasName("pk_margin_regulation_revisions");

                    b.HasIndex("SupersedesRevisionId")
                        .HasDatabaseName("ix_margin_regulation_revisions_supersedes_revision_id");

                    b.HasIndex("InstrumentId", "Revision")
                        .IsUnique()
                        .HasDatabaseName("ix_margin_regulation_revisions_instrument_id_revision");

                    b.ToTable("margin_regulation_revisions", (string)null);
                });

            modelBuilder.Entity("SwingAdviser.Domain.MarketData.CorporateAction", b =>
                {
                    b.HasOne("SwingAdviser.Domain.MarketData.Instrument", "Instrument")
                        .WithMany("CorporateActions")
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_corporate_actions_instruments_instrument_id");

                    b.HasOne("SwingAdviser.Domain.MarketData.CorporateAction", "Supersedes")
                        .WithMany()
                        .HasForeignKey("SupersedesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_corporate_actions_corporate_actions_supersedes_id");

                    b.Navigation("Instrument");

                    b.Navigation("Supersedes");
                });

            modelBuilder.Entity("SwingAdviser.Domain.MarketData.DailyBar", b =>
                {
                    b.HasOne("SwingAdviser.Domain.MarketData.Instrument", "Instrument")
                        .WithMany("DailyBars")
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_daily_bars_instruments_instrument_id");

                    b.HasOne("SwingAdviser.Domain.MarketData.DailyBar", "Supersedes")
                        .WithMany()
                        .HasForeignKey("SupersedesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_daily_bars_daily_bars_supersedes_id");

                    b.Navigation("Instrument");

                    b.Navigation("Supersedes");
                });

            modelBuilder.Entity("SwingAdviser.Domain.MarketData.FundamentalDataSnapshot", b =>
                {
                    b.HasOne("SwingAdviser.Domain.MarketData.Instrument", "Instrument")
                        .WithMany("FundamentalDataSnapshots")
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_fundamental_data_snapshots_instruments_instrument_id");

                    b.Navigation("Instrument");
                });

            modelBuilder.Entity("SwingAdviser.Domain.MarketData.InstrumentMasterRevision", b =>
                {
                    b.HasOne("SwingAdviser.Domain.MarketData.Instrument", "Instrument")
                        .WithMany("MasterRevisions")
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_instrument_master_revisions_instruments_instrument_id");

                    b.HasOne("SwingAdviser.Domain.MarketData.InstrumentMasterRevision", "SupersedesRevision")
                        .WithMany()
                        .HasForeignKey("SupersedesRevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_instrument_master_revisions_instrument_master_revisions_supersedes_revision_id");

                    b.Navigation("Instrument");

                    b.Navigation("SupersedesRevision");
                });

            modelBuilder.Entity("SwingAdviser.Domain.MarketData.MarginRegulationRevision", b =>
                {
                    b.HasOne("SwingAdviser.Domain.MarketData.Instrument", "Instrument")
                        .WithMany("MarginRegulationRevisions")
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_margin_regulation_revisions_instruments_instrument_id");

                    b.HasOne("SwingAdviser.Domain.MarketData.MarginRegulationRevision", "SupersedesRevision")
                        .WithMany()
                        .HasForeignKey("SupersedesRevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_margin_regulation_revisions_margin_regulation_revisions_supersedes_revision_id");

                    b.Navigation("Instrument");

                    b.Navigation("SupersedesRevision");
                });

            modelBuilder.Entity("SwingAdviser.Domain.MarketData.Instrument", b =>
                {
                    b.Navigation("CorporateActions");

                    b.Navigation("DailyBars");

                    b.Navigation("FundamentalDataSnapshots");

                    b.Navigation("MarginRegulationRevisions");

                    b.Navigation("MasterRevisions");
                });
#pragma warning restore 612, 618
        }
    }
}
