// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SwingAdviser.Infrastructure.Persistence;

#nullable disable

namespace SwingAdviser.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SwingAdviserDbContext))]
    partial class SwingAdviserDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.15");
#pragma warning restore 612, 618
        }
    }
}
